---
title: "Project"
author: "SangHeon Cha"
date: '2020 6 7 '
output: html_document
---

```{r}
library(httr)
library(tidyverse)
library(jsonlite)
library(rvest)
```

```{r}
url_list = vector()
url_list <- c(url_list, 1:20)
id_list = vector()
id_list <- c(id_list, 1:20)
name_list = vector()
name_list <- c(name_list, 1:20)
rating_list = vector()
rating_list <- c(rating_list, 1:20)

readRenviron(".Renviron")
r1 <- GET(
  "https://api.yelp.com/v3/businesses/search",
  add_headers(Authorization = paste("Bearer", Sys.getenv("YELP_KEY"))),
  query = list(
    location = "Davis",
    sort_by = "rating",
    limit = 20
  )
)
stop_for_status(r1)
json1 <- content(r1, as = "text", encoding = "UTF-8")
data1 <- fromJSON(json1, flatten = TRUE)
for (i in 1:20){
  url_list[i] <- data1$businesses[[6]][i]
  id_list[i] <- data1$businesses[[1]][i]
  name_list[i] <- data1$businesses[[3]][i]
  rating_list[i] <- data1$businesses[[9]][i]
}

data1$businesses[[4]][1]
rrr <- GET(
    data1$businesses[[4]][1]
  )
```

```{r}
index = c(1:20)
df=bind_cols(index, id_list) %>% 
  mutate(url_list) %>% 
  mutate(name_list) %>% 
  mutate(rating_list) %>% 
  rename(index = ...1) %>% 
  rename(id = ...2)
df1 = as.data.frame(df)
print(df[1,4])
```


```{r}
review_list = vector()
review_list <- c(review_list, 1:3)
rating_list = vector()
rating_list <- c(rating_list, 1:3)


r2 <- GET(
  paste0("https://api.yelp.com/v3/businesses/", id_list[1],"/reviews"),
  add_headers(Authorization = paste("Bearer", Sys.getenv("YELP_KEY")))
)
stop_for_status(r2)
json2 <- content(r2, as = "text", encoding = "UTF-8")
data2 <- fromJSON(json2, flatten = TRUE)
  for (j in 1:3){
    review_list[j] <- data2$reviews$text[j]
    rating_list[j] = data2$reviews$rating[j]
  }


        
        somename = df[1,4]

        n=1
        name = "La Cocina Mexicana Restaurant"
        some_name = df[1,4]
        while(n <= 20) {
            some_name = df[n,4]
            if (some_name == name) {
                break
            } else {
                n = n+1
            }
        }
```


